### ISSUE TITLE
SYSU-30k dataset

### ISSUE THREAD

**Issue by th0214** [wanggrun/triplet#4]
I want to train with SYSU-30k dataset, what should I do?

**Comment by wanggrun** [comment]
Dear @th0214 , thank you again for your interest in our paper. The organization of the SYSU-30k dataset is the same as ImageNet. Therefore, you only need to replace the data path in the config with the direction of the SYSU-30k dataset. The weights from ImageNet's self-supervised training can be used as weight initialization to speed up training. Since the SYSU-30k dataset is relatively large, you can set the number of training epochs to be small, such as 10-35 epochs.

Best regards,
