### ISSUE TITLE
code is incomplete

### ISSUE THREAD

**Issue by xing-ye** [wanggrun/triplet#5]
There seems to be some necessary code missing in `openselfsup.utils` such as `Registry` etc.

**Comment by wanggrun** [comment]
Dear @xing-ye , thanks for your interest in our work. The code is complete. After installing the environments of OpenSelfSup, you can run "pip install -v -e . " in the openselfsup folder of this repo. Note that there is an environment-dependency bug in the original openselfsup for Pytorch 1.9, and we have fixed the bug here.

Best regards,

**Comment by xing-ye** [comment]
Thanks a lot, I didn't actually configure the environment, sorry about that
